stages:
  - build
  - test

before_script:
  - mkdir -p build

build:
  artifacts:
    expire_in: 1 day
    paths:
      - build
  stage: build
  script:
    - cd build && cmake .. && make
    
test:
  stage: test
  dependencies:
    - build
  script:
    - cd build && ctest
