stages:
  - build
  - test

before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - cd build && cmake .. && make
  artifacts:
    paths:
      - build/
    expire_in: 1 week

test:
  stage: test
  script:
    - cd build && ctest

