before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - cd build && cmake ..
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build

test:
  stage: test
  script:
    - cd build && ctest
  after_script:
    - gcovr -r ..
  artifacts:
    reports:
      cobertura: coverage.xml
    paths:
      - build
