cache:
  untracked: true

build:
  stage: build
  script: cmake . && make

test-master:
  stage: test
  script: ctest
  only:
    - master

test-branches:
  stage: test
  script: ctest -R heat_seq
  except:
    - master

documentation:
  stage: deploy
  script: 
    - cmake . -DHEAT_DOC=ON
    - make doc
  allow_failure: true
  when: manual
  only:
    changes:
      - "*.c"
      - "*.h"
      - "doc/*"

