cache:
  paths:
    - /home/gitlab-runner/cache/project-namespace/project-name/cache-key

stages:
  - build
  - test

build:
  stage: build
  script:
    - cmake . && make

test:
  stage: test
  script:
    - ctest

