stages:
  - build
  - test

before_script:
  - mkdir -p build

build:
  stage: build
  script:
    - make
    - cd build
    - cmake .. -DCMAKE_C_FLAGS="--coverage" && make
    
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build

test:
  stage: test
  script:
    - cd build
    - ctest
    - gcovr -r ..
  artifacts:
    untracked: false
    when: on_success
    paths:
      - build
      - coverage.txt
