default:
  image: ubuntu

job1:
  image: tthor/heat
  script:
    - hostname
    - whoami
  tags: ['docker']

job2:
  image: tthor/test
  script:
    - hostname
    - whoami
  tags: ['docker']
job3:
  image: tthor/heat
  script:
    - cmake .
    - make
    - ctest
  tags: ['docker']
linux-gcc:
  variables:
    CC: gcc
    CXX: g++
  script:
    - cmake .
    - make
    - ctest

linux-clang:
  variables:
    CC: clang
    CXX: clang++
  script:
    - cmake .
    - make
    - ctest 
