default:
  image: tthor/heat
  tags: ['docker']

job1:
  image: tthor/heat
  script:
    - hostname
    - whoami
  tags: ['docker']

job2:
  image: tthor/test
  script:
    - hostname
    - whoami
  tags: ['docker']
job3:
  image: tthor/heat
  script:
    - cmake .
    - make
    - ctest
  tags: ['docker']
.build_test_script: &build_test_script
  script:
    - cmake .
    - make
    - ctest

linux-gcc:
  <<: *build_test_script
  variables:
    CC: "gcc"
    CXX: "g++"

linux-clang:
  <<: *build_test_script
  variables:
    CC: "clang"
    CXX: "clang++"

