default:
  image: ubuntu

job1:
  image: tthor/heat
  script:
    - hostname
    - whoami
  tags: ['docker']

job2:
  image: tthor/test
  script:
    - hostname
    - whoami
  tags: ['docker']
 job3:
  image: tthor/heat
  script:
    - cmake
    - make
    - ctest
  tags: ['docker']
